source 'https://rubygems.org'

gem 'jekyll', '4.0.0'
gem 'jekyll-theme-cloudcannon', :github => 'CloudCannon/jekyll-theme-cloudcannon', :branch => 'master'

group :jekyll_plugins do
	gem 'jekyll-archives', '>= 2.2.1'
	gem 'jekyll-paginate'
	gem 'jekyll-extract-element', '0.0.7'
	gem 'jekyll-shuffle', '0.0.2'
end